# Numpy Training

## Basics

In [2]:
import numpy as np

##### 1-D array

In [3]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


##### 2-D array

In [4]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


##### Get Dimension, Shape, DataType, Size

In [5]:
# get demension: 1-D, 2-D...
a.ndim

1

In [6]:
# get shape: number of rows and columns
b.shape

(2, 3)

In [7]:
# get datatype
# by default integer in python is 32 bits
a.dtype

# if originally we specify a to be 16 bits:
# a = np.array([1, 2, 3], dtype="int16")
# a.dtype
# result will be dtype('int16')

dtype('int64')

In [8]:
c = np.array([[1, 2, 3, 4, 5, 6, 7],[8, 9, 10, 11, 12, 13, 14]])
print(c)
c.shape

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


(2, 7)

In [9]:
# get specific element [row, column]
c[1, 5]
# result is 13
c[1, -3]
# result is 12

12

In [10]:
# get specific row
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
# get specific column
c[:, 2]

array([ 3, 10])

In [12]:
# get a little more fancy [startindex:endindex:stepsize]
c[0, 1:6:2]

array([2, 4, 6])

In [13]:
# change element
c[1, 5] = 20
print(c)

# change entire column
c[:, 2] = [1, 2]
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


##### 3-D Example

In [14]:
d = np.array([[[1, 2],[3, 4]],[[5, 6],[7, 8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
# get specific element (work outside in)
# example if we want to get element 4
d[0, 1, 1]

4

In [16]:
# replace elements
d[:, 1, :] = [[9, 9], [8, 8]]
print(d)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## Initializing Differnet Types of Arrays

In [17]:
# all 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
# all ones matrix
np.ones((2, 3, 2), dtype='int32')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int32)

In [20]:
# any other number, first element is the shape, second element is the value
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [21]:
# matrix of random decimal numbers - we just need to enter the shape so only one pair of ()
np.random.rand(4, 2)

array([[0.0100349 , 0.06836417],
       [0.71726563, 0.26214894],
       [0.89600645, 0.00404518],
       [0.64197811, 0.18149343]])

In [22]:
# matrix of random integer values
# if you enter 2 values, it specifies start and finish values but if you enter one number, it starts at zero to specified number
# if we don't specify size it only gonna give us one number
e = np.random.randint(-5, 10)
print(e)

f = np.random.randint(7, size = (3, 2))
print(f)

0
[[2 0]
 [0 3]
 [0 5]]


In [23]:
# identity matrix - we need only one number because its square matrix by nature
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
# repeat array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [25]:
# example
output = np.ones((5, 5))
print(output)

z = np.zeros((3, 3))
z[1, 1] = 9
print(z)

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [26]:
# be careful when copying arrays

# g = np.array([1, 2, 3])
# h = g
# h[0] = 100
# print(g)
# print(h)
# as you can see it changes on both arrays because h is pointing to same array to prevent this we need to make a copy

g = np.array([1, 2, 3])
h = g.copy()
h[0] = 100
print(g)
print(h)
# now we are only copying the contents of array g to array h and this will not change anything on array g

[1 2 3]
[100   2   3]


## Mathematics

##### Arithmetic

In [36]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [37]:
a + 2

array([3, 4, 5, 6])

In [38]:
a - 2

array([-1,  0,  1,  2])

In [39]:
a * 2

array([2, 4, 6, 8])

In [40]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [41]:
a ** 2

array([ 1,  4,  9, 16])

In [42]:
b = np.array([1, 0, 1, 0])

a + b

array([2, 2, 4, 4])

In [43]:
# calculate the sin(a), cos(a)

print(np.sin(a))
print(np.cos(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [44]:
# for more functions

# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [45]:
#Multiplying 2 matrix
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

# for multiplying 2 matrix, if they are not same size, the number of rows on first matrix should equal to columns on second matrix
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [46]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [47]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [48]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
np.min(stats)

1

In [50]:
#get min on row bases
np.min(stats, axis = 1)

array([1, 4])

In [51]:
np.max(stats)

6

In [52]:
# get max on row bases
np.max(stats, axis = 1)

array([3, 6])

In [53]:
np.sum(stats)

21

In [54]:
# sum by column
print(np.sum(stats, axis = 0))

# sum by row
print(np.sum(stats, axis = 1))

[5 7 9]
[ 6 15]


## Reorganising arrays

##### Reshape

In [55]:
# Reshape

before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)

after = before.reshape((8, 1))
print(after)
print(after.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
(8, 1)


##### Vertical Stacking vectors

In [57]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

##### Horizontal stacking

In [58]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])